#!/bin/bash
while read oldrev newrev ref
do
	if [[ $ref =~ ./*master$ ]];
	then
		echo "Master ref received. Deploying master branch to production..."
		git --git-dir=/home/git/repo --work-tree=/home/git/content checkout -f
		curl -X POST http://pelican/update
	else
		echo "Ref $ref successfully received. Doing nothing..."
	fi
done

